### ISSUE TITLE
空的 background: url()

### ISSUE THREAD

**Issue by rwu823** [design-team-cepave/OWL-UI-lite#1]
疑似這邊?
https://github.com/design-team-cepave/OWL-UI-lite/blob/master/src/sass/_scss/components/_icons.scss#L11

```css
.lt-ie9 .icon.icon-alarm, .lt-ie9 .icon.icon-arrow-down, .lt-ie9 .icon.icon-arrow-up, .lt-ie9 .icon.icon-bell, .lt-ie9 .icon.icon-bin, .lt-ie9 .icon.icon-board, .lt-ie9 .icon.icon-check, .lt-ie9 .icon.icon-chevron-left, ... {
  background-image: url();
}
```
